#!/bin/zsh

# List of configurations
configs=("i3" "polybar" "nvim" "ranger")

# Function to open config folder in a new Kitty terminal
open_config() {
    case "$1" in
        "i3")
            kitty nvim ~/.config/i3/config
            ;;
        "polybar")
            kitty nvim ~/.config/polybar/config.ini
            ;;
        "nvim")
            kitty nvim ~/.config/nvim
            ;;
        "ranger")
            kitty nvim ~/.config/ranger
            ;;
        *)
            echo "Invalid option"
            ;;
    esac
}

# Show menu using Rofi
selected_config=$(printf "%s\n" "${configs[@]}" | rofi -dmenu -p "Select config:")

# Open selected config in a new Kitty terminal
open_config "$selected_config"

