#!/bin/zsh
# https://github.com/ankitpokhrel/jira-cli < install this
# brew tap ankitpokhrel/jira-cli
# brew install jira-cli
# https://id.atlassian.com/manage-profile/security/api-tokens
# zshenv -> export JIRA_API_TOKEN=XXX
# DONT PUT JIRA_AUTH_TYPE=bearer for cloud server to save your hairline
# jira init --installation cloud --server "https://XXX.atlassian.net" --login "XXX" --debug
# chmod +x & alias this script in your .zshrc alias tiksu='$USER/scripts/tiksu' or so

echo Tiksun otsikko
read title
echo Tiksun kuvaus
read description

TICKET=$(jira issue create -tTask -s"$title" -b"$description" --no-input | tail -1 | sed 's|.*/||')

jira issue assign $TICKET $(jira me)

SPRINT=$(jira sprint list --table | grep active | sed 's/\t.*//')

#not working atm
#jira sprint add $SPRINT $TICKET
xdg-open https://postinext.atlassian.net/browse/$TICKET

#jira issue view $TICKET
