#!/usr/bin/zsh
# Update the environment variables
export WORK_MONITOR="DP-2-1"
export SIDE_MONITOR="DP-2-3"

sed -i "s/^export WORK_MONITOR=.*/export WORK_MONITOR=\"$WORK_MONITOR\"/" ~/.zshenv
sed -i "s/^export SIDE_MONITOR=.*/export SIDE_MONITOR=\"$SIDE_MONITOR\"/" ~/.zshenv

mleft

autorandr home
~/scripts/home_screens.sh
