#!/usr/bin/zsh
# Update the environment variables
export WORK_MONITOR="DP-6"
export SIDE_MONITOR="DP-8"

hyprctl keyword monitor "DP-6, 2560x1440, 1080x0, 1"
hyprctl keyword monitor "DP-8, 1920x1080, 0x0, 1, transform, 3"
hyprctl keyword monitor "eDP-1, disable"

sed -i "s/^export WORK_MONITOR=.*/export WORK_MONITOR=\"$WORK_MONITOR\"/" ~/.zshenv
sed -i "s/^export SIDE_MONITOR=.*/export SIDE_MONITOR=\"$SIDE_MONITOR\"/" ~/.zshenv
