#!/usr/bin/zsh
# Update the environment variables
export WORK_MONITOR="eDP-1"
export SIDE_MONITOR=""
mright

sed -i "s/^export WORK_MONITOR=.*/export WORK_MONITOR=\"$WORK_MONITOR\"/" ~/.zshenv
sed -i "s/^export SIDE_MONITOR=.*/export SIDE_MONITOR=\"$SIDE_MONITOR\"/" ~/.zshenv

autorandr solo
~/scripts/home_screens.sh


